spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
    properties:
      sslMode: REQUIRE

server:
  port: ${PORT:}
